name: build
run-name: Build triggered by ${{ github.actor }}_${{ github.event_name }}_${{ github.ref }}
description: |
  This is a workflow for testing out GitHub Actions.
  It will run on every push to the main branch and on pull requests.
  It will also run on merge groups
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  merge_group:
  push:
    branches:
      - main
      - dev
      - feature/*
      - release/*
    paths:
      - 'src/**'
      - '!docs/**'
      - '.github/**'


concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

env:
  artifact_name: 'web-app-build-artifact'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository code (Workflow version: Main)"
        uses: actions/checkout@v4
      - name: "🚀 Displaying GitHub Context Variables."
        id: get_context
        uses: ./.github/actions/github-context
        with:
          message: "🔑 Displaying GitHub Context Variables"
      - name: "Display Context Message"
        run: |
          echo "🔑 The message from the previous step is: ${{ steps.get_context.outputs.message }}"

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    environment: DEV
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: | 
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          echo "🖥️ The workflow is now ready to test your code on the runner."
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 🫙Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/web-app/*.csproj') }}

      - name: 🔄 Restore dependencies
        working-directory: ${{ github.workspace }}/src/web-app
        run: |
          echo "🔄 Restoring dependencies for the .NET project."
          dotnet restore

      - name: 🔨 Build Application
        working-directory: ${{ github.workspace }}/src/web-app
        run: |
          echo "🔨 Building the .NET project."
          dotnet build --no-restore --configuration Release

      - name: 🔍 Run Tests
        working-directory: ${{ github.workspace }}/src/web-app
        run: |
          echo "🔍 Running tests"
          dotnet test --no-build --configuration Release --verbosity normal

      - name: 📢 Publish Application
        working-directory: ${{ github.workspace }}/src/web-app
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: ⬆️ Upload Build Artifacts - GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: ./src/web-app/publish
          retention-days: 5

      - name: 🗜️ Zip Folder
        run: |
          # name of the zip file can be replaced with hash of the commit to support versioning
          cd ${{ github.workspace }}/src/web-app/publish
          zip -r ../${{ env.artifact_name }}.zip .

      - name: 📦 Upload Build Artifact - Azure Storage
        uses: bacongobbler/azure-blob-storage-upload@a7f1705d5d3796a387d18cae8e6864ae3d021bda # v3.0.0
        with:
          connection_string : ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          source_dir: '${{ github.workspace }}/src/web-app'
          container_name: artifacts
          extra_args: '--pattern *.zip'
          overwrite: 'true'

  release:
    name: release
    needs: [build]
    if: ${{ !failure() && !cancelled() }}
    uses: ./.github/workflows/release.yml
    with:
      artifact_name: 'web-app-build-artifact'
    secrets: inherit